[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "approvaltests>=14.3.1",
    "coverage>=7.7.0",
    "pytest>=8.3.5",
    "pytest-approvaltests>=0.2.4",
]
